
name: Test PR label to issue

on:
  pull_request:
    types:
      - closed
      - opened

jobs:
  docbot:
    runs-on: ubuntu-latest
    name: Create issue on doc repo for labeled issue
    # if: github.event.pull_request.merged && contains( github.event.pull_request.labels.*.name, 'documentation')
    steps:
      - name: debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: QGIS milestone to Doc label 2
        id: milestone2label2
        env:
          MILESTONE: ${{ github.event.pull_request.milestone.title }}
        run: |
          LABEL=$(sed -r 's/^([[:digit:]]\.[[:digit:]]+)(\.[[:digit:]]+)?$/\1/' <<< ${MILESTONE})
          echo $(sed -r 's/^([[:digit:]]\.[[:digit:]]+)(\.[[:digit:]]+)?$/\1/' <<< ${MILESTONE})
          echo `sed -r 's/^([[:digit:]]\.[[:digit:]]+)(\.[[:digit:]]+)?$/\1/' <<< ${MILESTONE}`
          echo ${LABEL}
          echo "::set-output name=label::${LABEL}"

      - name: output
        run: echo ${{ steps.milestone2label2.outputs.label }}

      - name: Clear GH Token
        id: token
        uses: opengisch/clear-token@v1.0.12
        with:
          bot_token_encrypted: ddbdec32940df79f1adf2369b4b10f10b5a66f65
          bot_token_xor_key: a1b2c3d47311f8e29e204f85a81b4df4a44e252c

      - name: Create Documentation issue
        id: doc_issue
        uses: maxkomarychev/oction-create-issue@v0.7.1
        with:
          token: ${{ steps.token.outputs.token }}
          title: ${{ format('Request in QGIS ({0})', github.event.pull_request.title) }}
          labels: 3.12
          # labels: ${{ steps.milestone2label.outputs.label }}
          body: |
            ${{ format('Request for documentation in QGIS/qgis#{0})', github.event.pull_request.number) }}
            ${{ github.event.pull_request.title }}


      - name: Print outputs
        run: |
          echo ${{ steps.doc_issue.outputs.id }}
          echo ${{ steps.doc_issue.outputs.number }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ steps.token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @${{ github.event.pull_request.user.login }}
            A documentation ticket has been opened at https://github.com/qgis/QGIS-Documentation/issue/${{ steps.doc_issue.outputs.number }}
            It is **your** responsibility to visit this ticket and add as much detail as possible for the documentation team to correctly document this change.
            Thank you!
          reaction-type: 'rocket'

